# Generated by Django 3.0.9 on 2020-08-17 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20200816_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='revision_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revision_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='revision_date',
            field=models.DateTimeField(null=True),
        ),
    ]
